---
- name: install lamp server in ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: install and update apache
      package:
       name: apache2
       update_cache: yes
       state: present
    - name: install php
      package:
        name: php
        state: present
    - name: install libapache2-mod-php
      apt:
        name: libapache2-mod-php
        state: present
    - name: install php-mysql
      apt:
        name: php-mysql
        state: present
    - name: install php-cli
      apt:
        name: php-cli
        state: present
    - name: copy info.php
      copy:
        src: info.php
        dest: /var/www/html/info.php
- name: install lamp on centos 
  hosts: centos
  become: yes
  tasks:
   - name: install httpd
     package:
       name: httpd
       state: present
   - name: start and enable httpd
     ansible.builtin.service:
       name: httpd
       enabled: yes  
       state: started
   - name: install php
     package:
        name: php
        state: present
   - name: install php-mysql
     apt:
        name: php-mysql
        state: present
   - name: install php-fpm
     apt:
        name: php-fpm
        state: present
   - name: copy info.php
     copy:
       src: info.php
       dest: /var/www/html/info.php 



