---
- name: install utility sosftwares
  hosts: all
  become: yes
  tasks:
    - name: install git
      package:
        name: git
        state: present
    - name: install tree
      package: 
        name: tree
        state: present
    - name: install nano
      package: 
        name: nano
        state: present        
- name: install apache on centos
  hosts: centos
  become: yes
  tasks:
   - name: install apache
     package:
       name: httpd
       state: present
   - name: Enable service httpd, and not touch the state
     ansible.builtin.service:
       name: httpd
       enabled: yes  
       state: started 
          