---
- name: install lamp stack
  hosts: webserver
  become: yes
  tasks:
    - name: install apache
      package:
        name: "{{ package_name }}"
        state: present
    - name: install php packages
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_packages }}"    